### ISSUE TITLE
Update aspect ratio on canvas resize

### ISSUE THREAD

**Issue by tobychui** [aligator/gcode-viewer#1]
Hi there!

I was trying to integrate this gcode viewer into the [SlicerA](https://github.com/tobychui/SlicerA) and observed an issue when I attach window resize events to the canvas. 
![2021-05-06_10-40-08](https://user-images.githubusercontent.com/24617523/117234441-962f4480-ae57-11eb-9aeb-a8c81e19c3d1.png)

Would it be possible for you to add an automatic logic for adjusting the aspect ratio when the DOM element resized? Thanks!

**Comment by aligator** [comment]
Just call `renderer.resize(width, height)` whenever you want to resize it. Then the camera will be recalculated. I needed the same for my website and it works just fine: https://github.com/aligator/dev/blob/45374ff9f2b1d3ac96bbfac9bd64182cf3451a4f/src/windows/gCodeViewer.tsx#L64

**Comment by tobychui** [comment]
I have updated the implementation of gcode viewer in SlicerA using your website source code as example. Thanks so much for the tips!
