### ISSUE TITLE
Relative Extrusion not supported

### ISSUE THREAD

**Issue by temekoglu** [aligator/gcode-viewer#15]
Hi. Gcode viewer has bug. (I think bug only works if gcode rendered by PrusaSlicer. I don't knıw.) 

I added gcode and screenshots below

<img width="799" alt="Screen Shot 2022-07-31 at 22 19 35" src="https://user-images.githubusercontent.com/39217313/182041842-7eece411-f556-4847-94bc-1c600a92c4d8.png">

[lenst.gcode.zip](https://github.com/aligator/gcode-viewer/files/9229571/lenst.gcode.zip)

**Comment by aligator** [comment]
Hi, thanks.

Maybe these are just so small extrusions, that they are just not drawn perfectly?
I will look into it when I have time.

**Comment by temekoglu** [comment]
Thank you. I am waiting for news from you.

**Comment by temekoglu** [comment]
and the product is not too small, but large enough. I added screenshot (I can successfully view on other sites)

<img width="682" alt="Screen Shot 2022-08-03 at 08 57 29" src="https://user-images.githubusercontent.com/39217313/182534908-fbf895c4-85ce-4806-a51e-b8cc32700ced.png">

**Comment by temekoglu** [comment]
@aligator any news?

**Comment by aligator** [comment]
Sorry, I had no time for this yet...

**Comment by temekoglu** [comment]
Can you give me an estimated date? I had to suspend my project and cannot progress.
If it's going to take too long, I'll look for another library. @aligator

**Comment by aligator** [comment]
Sorry, but this is one of my many hobby projects so I cannot promise any specific date. 

However, I will look into it tomorrow and will let you know when I know more about the issue.

**Comment by aligator** [comment]
@temekoglu 
The problem is that I initially built this only for my own, experimental slicer (as stated in the readme). That slicer only outputs absolute extrusions, not relative.

Could you verify this by setting the extrusion to absolute in cura?
I already have an untested code-path for this in the viewer. It improves the result, but there are still several errors:

There may be more special gcodes which are not handled, yet. (e.g. inch-units G20)

![Screenshot_2022-08-25_09-16-40](https://user-images.githubusercontent.com/663900/186600781-3a164df1-724a-46fa-9c3c-b841455f3183.png)

**Comment by aligator** [comment]
@temekoglu 
Good news, after just hiding all negative extrusions:
![Screenshot_2022-08-25_09-58-15](https://user-images.githubusercontent.com/663900/186608963-2ee83c1e-4a59-4160-b42a-0a7d5ab4ff43.png)

I will release that as a new version, which you can test

**Comment by aligator** [comment]
@temekoglu
Done :+1: 
Could you please test it?

**Comment by temekoglu** [comment]
Thanks. Yes I'll.

**Comment by temekoglu** [comment]
Looking good. Thank you for update.
<img width="828" alt="Screen Shot 2022-08-25 at 13 29 30" src="https://user-images.githubusercontent.com/39217313/186642480-1345fbdd-2ddb-4742-87f6-0e9503c79993.png">

**Comment by aligator** [comment]
Nice 👍
If you find any other unsupported gcode, please tell me😃
