### ISSUE TITLE
HTML frontEnd webPage with controls

### ISSUE THREAD

**Issue by yvanblanchard** [aligator/gcode-viewer#19]
Hello,

Good work!
Is it possible to have an example with webPage (HTML) with buttons controls ? for changing current layer, etc. 
I'm not so familiar with JS...

Thank you.

**Comment by aligator** [comment]
I added a bit more extended example:
https://github.com/aligator/gcode-viewer/blob/main/example/extended.html

I hope that helps you.

**Comment by yvanblanchard** [comment]
That's very nice!
thank you

![image](https://user-images.githubusercontent.com/63931618/212847728-96efe0a8-75e4-4032-8f3b-69926ec9347d.png)
