### ISSUE TITLE
points of a layer

### ISSUE THREAD

**Issue by cover1012** [aligator/gcode-viewer#22]
Hello,

Is it possible to get the points of a certain layer? For example: Layer 5 starts at point 6544 and ends at point 11322. What I want is to render starting from a layer and ending at a point.

Thanks for helping.

**Comment by aligator** [comment]
Hi, you can use renderer.sliceLayer(minLayer, maxLayer) to only display a certain range of layers.
Or you can use renderer.slice(minPointNr, maxPointNr)  to slice at specific points.

If you need something different, let me know :-)

If you need the info which layer starts at which point, I cold expose that information, as it is avalable in the lib as private.

**Comment by cover1012** [comment]
If you need the info which layer starts at which point, I cold expose that information, as it is avalable in the lib as private.

Originally posted by @aligator in https://github.com/aligator/gcode-viewer/issues/22#issuecomment-1537384811

That would be great!

**Comment by aligator** [comment]
Ok I will look into it the next days

**Comment by aligator** [comment]
@cover1012 
Could you please try if it is now possible to do what you need?

> To get information about the start and end of specific layers, you can use:
> renderer.getLayerDefinition(layerIndex)
> 
> Or to get all layer definitions at once:
> renderer.getLayerDefinitions()
> renderer.getLayerDefinitionsNoCopy() (use only if you know what you are doing)
> 
> Note: The layer definitions are only available after the first render.

**Comment by cover1012** [comment]
Thanks very much. This is exactly what i need.
